# ===================================================================
# GitHub Actions Workflow: Docker Publish (AMD64 Only)
# ===================================================================
# This workflow builds and publishes amd64 Docker images.
#
# It consists of two main jobs:
# 1. 'build-lite': Builds a lightweight amd64 base image. This image is
#    used for caching and as a base for the full image.
# 2. 'build-full-and-deploy': Waits for 'build-lite' to complete. It then
#    builds the full-featured amd64 image using the 'lite' image as its
#    base. It pushes the final image with appropriate tags, including
#    'latest' for pushes to the master branch.
# ===================================================================

name: Docker Publish

# Workflow triggers
on:
  push:
    branches:
      - 'master' # Push to master branch
      - 'main'   # Push to main branch
    tags:
      - 'v*.*.*' # Any version tag push (e.g., v1.0.0)
  pull_request:
    branches:
      - 'master'
      - 'main'

# Environment variables available to all jobs
env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  # ===================================================================
  # JOB 1: Build the 'lite' base image (amd64)
  # ===================================================================
  build-lite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker (tags and labels) for lite image
        id: meta-lite
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch,suffix=-lite
            type=ref,event=tag,suffix=-lite

      - name: Build and push 'lite' image (amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.lite
          # ===================================================================
          # **核心修改 1**
          # 强制在模拟的 x86-64 v2 (支持 AVX, 但不支持 AVX2) 平台上构建。
          # 这模拟了 'docker-noavx2' Runner 的效果，确保了最大兼容性。
          # ===================================================================
          platforms: linux/amd64/v2
          push: true
          tags: ${{ steps.meta-lite.outputs.tags }}
          labels: ${{ steps.meta-lite.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:lite-buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:lite-buildcache,mode=max

  # ===================================================================
  # JOB 2: Build the 'full' image and deploy (amd64)
  # ===================================================================
  build-full-and-deploy:
    runs-on: ubuntu-latest
    needs: build-lite
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker (tags and labels) for full image
        id: meta-full
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=schedule
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=full,enable={{is_default_branch}}

      - name: Determine base image tag
        id: base_tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "tag=${{ github.ref_name }}-lite" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.ref_name }}-lite" >> $GITHUB_OUTPUT
          fi

      - name: Build and push 'full' image (amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          # ===================================================================
          # **核心修改 2**
          # 同样，强制在 v2 平台上构建 'full' 镜像。
          # ===================================================================
          platforms: linux/amd64/v2
          build-args: |
            BASE_IMAGE=${{ env.DOCKER_IMAGE }}:${{ steps.base_tag.outputs.tag }}
          push: true
          tags: ${{ steps.meta-full.outputs.tags }}
          labels: ${{ steps.meta-full.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:full-buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:full-buildcache,mode=max
