name: Docker Publish

# Workflow triggers
on:
  push:
    branches:
      - '**' # Any branch push
    tags:
      - 'v*.*.*' # Any version tag push
  pull_request:
    branches:
      - 'master' # PRs targeting master

# Environment variables
env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  # --- Build Job ---
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            arch: amd64
          - platform: linux/arm64
            arch: arm64
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ** FIX: Separate metadata generation for each image variant **
      - name: Extract metadata for 'lite' image
        id: meta_lite
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch,suffix=-{{matrix.arch}}-lite
            type=ref,event=tag,suffix=-{{matrix.arch}}-lite

      - name: Extract metadata for 'full' image
        id: meta_full
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch,suffix=-{{matrix.arch}}-full
            type=ref,event=tag,suffix=-{{matrix.arch}}-full

      - name: Build and push 'lite' image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.lite
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta_lite.outputs.tags }}
          labels: ${{ steps.meta_lite.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:${{ matrix.arch }}-lite-buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:${{ matrix.arch }}-lite-buildcache,mode=max

      - name: Build and push 'full' image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            BASE_IMAGE=${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}-${{ matrix.arch }}-lite
          push: true
          tags: ${{ steps.meta_full.outputs.tags }}
          labels: ${{ steps.meta_full.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:${{ matrix.arch }}-full-buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:${{ matrix.arch }}-full-buildcache,mode=max

  # --- Deploy Job ---
  deploy:
    runs-on: ubuntu-latest
    needs: build # This job runs only after the 'build' job completes successfully
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get sanitized branch/tag name
        id: get_name
        run: echo "ref_name=$(echo ${{ github.ref_name }} | sed -e 's/[^a-zA-Z0-9.-]/-/g')" >> $GITHUB_ENV

      - name: Create and push 'lite' manifest
        run: |
          docker manifest create ${{ env.DOCKER_IMAGE }}:${{ env.ref_name }}-lite \
            ${{ env.DOCKER_IMAGE }}:${{ env.ref_name }}-amd64-lite \
            ${{ env.DOCKER_IMAGE }}:${{ env.ref_name }}-arm64-lite
          docker manifest push ${{ env.DOCKER_IMAGE }}:${{ env.ref_name }}-lite

      - name: Create and push 'full' & branch manifest
        run: |
          docker manifest create ${{ env.DOCKER_IMAGE }}:${{ env.ref_name }}-full \
            ${{ env.DOCKER_IMAGE }}:${{ env.ref_name }}-amd64-full \
            ${{ env.DOCKER_IMAGE }}:${{ env.ref_name }}-arm64-full
          docker manifest push ${{ env.DOCKER_IMAGE }}:${{ env.ref_name }}-full
          docker manifest push ${{ env.DOCKER_IMAGE }}:${{ env.ref_name }}

      - name: Create and push 'latest-lite' manifest
        if: github.ref == 'refs/heads/master'
        run: |
          docker manifest create ${{ env.DOCKER_IMAGE }}:lite \
            ${{ env.DOCKER_IMAGE }}:master-amd64-lite \
            ${{ env.DOCKER_IMAGE }}:master-arm64-lite
          docker manifest push ${{ env.DOCKER_IMAGE }}:lite

      - name: Create and push 'latest-full' & 'latest' manifest
        if: github.ref == 'refs/heads/master'
        run: |
          docker manifest create ${{ env.DOCKER_IMAGE }}:full \
            ${{ env.DOCKER_IMAGE }}:master-amd64-full \
            ${{ env.DOCKER_IMAGE }}:master-arm64-full
          docker manifest push ${{ env.DOCKER_IMAGE }}:full
          docker manifest push ${{ env.DOCKER_IMAGE }}:latest
